plugins {
    id 'com.android.application'
}
android {
    namespace 'io.github.francescobrina.portdrift'
    compileSdk 37
    defaultConfig {
        applicationId 'io.github.francescobrina.portdrift'
        minSdk 28
        targetSdk 37
        versionCode 6
        versionName '0.5.1-beta.2'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    testImplementation 'junit:junit:4.13.2'
}
